apiVersion: v1
kind: Service
metadata:
  name: frontend2301-service
  labels:
    app: frontend2301
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: frontend2301