apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2301-deployment
  labels:
    app: frontend2301
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend2301
  template:
    metadata:
      labels:
        app: frontend2301
    spec:
      containers:
      - name: frontend2301
        image: navin360/frontend2201
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://ab79d3f27e4a04aed98dbf794a74b366-411797331.ap-northeast-1.elb.amazonaws.com:8706"
